### ISSUE TITLE
Can you add support for windows os

### ISSUE THREAD

**Issue by rakhinskiy** [mscdex/sipster#16]
Why you dont support windows version?

Currntly pjsip (pjsua2) support windows platform

**Comment by mscdex** [comment]
1. My main use case for this project is for *nix, so Windows is not really a priority.
2. It's unclear how well pjsip/pjsua2 supports newer versions of VS required by the likes of node v4+.
3. From what I can tell by reading the pjsip documentation, it is not easy to build pjsip (shared libraries) on Windows.
4. I'm not familiar with the difficulty of linking to shared libraries on Windows via gyp (e.g. if hardcoded absolute paths are needed, etc.).

**Comment by StrikeForceZero** [comment]
I was looking at doing the same thing I did for [this](https://github.com/StrikeForceZero/PJSip-CSharp) using [swig](http://www.swig.org/Doc3.0/Javascript.html). But I ran into a few snags for nodejs. may have been an issue with swig use of outdated nodejs classes?

In theory if one could compile the shared library under gyp then you could use pjsip cross platform via nodejs with little to no problems.
