### ISSUE TITLE
Porting to Windows

### ISSUE THREAD

**Issue by bitsoflogic** [mscdex/sipster#2]
From your experience in setting this up, what's the difficulty in getting sipster working on Windows?  I've been exploring a lot of pjsip wrappers and really like what you've done here.

**Comment by StrikeForceZero** [comment]
For anyone feeling froggy you could probably achieve windows compatibility if you can solve [pjsip and swig for nodejs](http://www.swig.org/Doc3.0/Javascript.html) as [mentioned](https://github.com/mscdex/sipster/issues/16#issuecomment-195566087) in #16

**Comment by StrikeForceZero** [comment]
_[ Cut and moved to #23 ]_
