### ISSUE TITLE
Sample program Runnig Failed

### ISSUE THREAD

**Issue by DhirajDJ** [mscdex/sipster#20]
Hi, 
I have installed sipster successfully and my pjsip is installed at default location(/usr/local/).
I have followed your earlier guidelines to install sipster. 
Thanks a lot for that.
But at the time of running sample program given by you I am facing problem.
I am getting error like this:

module.js:460
  return process.dlopen(module, path._makeLong(filename));
                 ^
Error: libpjsua2.so.2: cannot open shared object file: No such file or directory
at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/root/test/node_modules/sipster/lib/main.js:4:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

But I have checked that libpjsua2.so.2 file is available at /usr/local/lib.
Can you please help me regarding this?

**Comment by mscdex** [comment]
You may try manually updating the ld.so.cache by running `ldconfig`.

If it still can't find it, you should verify `/usr/local/lib` is in your shared library search path. You can check that by checking if this outputs `/usr/local/lib`: `ldconfig -v 2>/dev/null | grep -v ^$'\t' | grep -iF "/usr/local/lib"`

**Comment by DhirajDJ** [comment]
Thank you very much for your earliest response. 
Thanks again your solution worked for me.

**Comment by DhirajDJ** [comment]
Hi Brian,

Your solution worked for me. 
We want to develop SIP server using NodeJS for that we want to use PJSIP as stack.
So, I have already worked on PJSIP for building SIP server but our SIP server is based on C. 
So we want to work on NodeJS based SIP server.  For that we need your help for accessing low level pjsip api to access from Node. 
So, will you be interested to help us regarding this ?
If you are interested please share your mail id so that we can discuss more. 

Best regards, 
Dhiraj

**Comment by glebpavlov** [comment]
#ldconfig

**Comment by hthetiot** [comment]
```bash
export LD_LIBRARY_PATH="/usr/local/lib"
```
Did the trick on Ubuntu 16.04
