### ISSUE TITLE
How to connect to my sip account?

### ISSUE THREAD

**Issue by bloodcarter** [mscdex/sipster#30]
I'm using this config, but it just doesn't react to incoming calls, nothing.

```
var acct = new sipster.Account({
  idUri: 'sip:xxxxxx@sip.zadarma.com',
    regConfig: {
    registrarUri: 'sip:sip.zadarma.com'
  },
  sipConfig: {
    authCreds: [{
      scheme: 'digest',
      realm: 'myrealm',
      username: 'xxxxxx',
      dataType: 0, // plain text password
      data: 'xxxxxx'
    }]
  }
});
```

**Comment by mscdex** [comment]
The UAC scenario is not tested. The original use case for this addon was for UAS (a trunk receiving calls).

**Comment by bloodcarter** [comment]
@mscdex Thanks for response. Could you show me where to start in order to add this feature? I need making outbound calls and read/write the the stream.
