### ISSUE TITLE
why can't i heard the remote ,and the remote can't heard me ether...

### ISSUE THREAD

**Issue by chengzi201412** [mscdex/sipster#9]
e,
I use it in window 7 environment

**Comment by chengzi201412** [comment]
@mscdex 
I don't know what is the reason,can you help me? 
thanks.

**Comment by mscdex** [comment]
I haven't tested the `makeCall()` very much since that was not my original use case.

**Comment by chengzi201412** [comment]
@mscdex 
I have found the reason yet,in the function of 'EPinit' you add this code:Endpoint::instance().audDevManager().setNullDev();.
so the system will open null sound device ,and i delete this code, after makecall to remote ,we heard each other now.
Thank you very much.
